version: "1.0"

services:
  postgres:
    image: postgres:latest
    container_name: book-store-postgres
    volumes:
      - dbdata:/data/db
    environment:
      POSTGRES_DB: "book-store"
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"

volumes:
  dbdata:
