-- CreateEnum
CREATE TYPE "Genre" AS ENUM ('FANTASY', 'ADVENTURE', 'ROMANCE', 'CONTEMPORARY', 'DYSTOPIAN', 'MYSTERY', 'HORROR', 'THRILLER', 'PARANORMAL', 'HISTORICAL_FICTION', 'SCIENCE_FICTION', 'MEMOIR', 'COOKBOOK', 'ART', 'SELF_HELP', 'DEVELOPMENT', 'HEALTH', 'MOTIVATION', 'HISTORY', 'TRAVEL', 'GUIDE', 'HUMOR');

-- AlterTable
ALTER TABLE "book" ADD COLUMN     "genre" "Genre"[];

-- CreateTable
CREATE TABLE "Comment" (
    "id" BIGSERIAL NOT NULL,
    "content" TEXT NOT NULL,
    "bookId" INTEGER NOT NULL,
    "userId" INTEGER NOT NULL,

    CONSTRAINT "Comment_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Comment" ADD CONSTRAINT "Comment_bookId_fkey" FOREIGN KEY ("bookId") REFERENCES "book"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Comment" ADD CONSTRAINT "Comment_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
